API_PREFIX = ""
DEFAULT_REST_API_INTERFACE = "0.0.0.0"
DEFAULT_REST_API_PORT = 12000

DEFAULT_LOGGING_LEVEL = "INFO"
DEFAULT_OUTPUT_STREAM_PORT = 8889

DEFAULT_ROI = []
DEFAULT_PARAMETERS = {
    "background": ""
}

PROCESSOR_START_TIMEOUT = 1

INPUT_STREAM_QUEUE_SIZE = 100
INPUT_STREAM_RECEIVE_TIMEOUT = 1000
OUTPUT_STREAM_SEND_TIMEOUT = 1000

EPICS_PV_SUFFIX_IMAGE = ":FPICTURE"

DEFAULT_CAMERA_IMAGE_COLORMAP = "rainbow"

DEFAULT_INPUT_PV = "SARFE10-PSSS059"
DEFAULT_OUTPUT_PV = "SARFE10-PSSS059:SPECTRUM_Y"
DEFAULT_AXIS_PV = "SARFE10-PSSS059:SPECTRUM_X"

DEFAULT_YMIN_PV = "SARFE10-PSSS059:SPC_ROI_YMIN"
DEFAULT_YMAX_PV = "SARFE10-PSSS059:SPC_ROI_YMAX"

