API_PREFIX = ""
DEFAULT_REST_API_INTERFACE = "0.0.0.0"
DEFAULT_REST_API_PORT = 12000

DEFAULT_LOGGING_LEVEL = "INFO"
DEFAULT_OUTPUT_STREAM_PORT = 8889

DEFAULT_ROI = []
DEFAULT_PARAMETERS = {"min_threshold": 0,
                      "max_threshold": 0,
                      "rotation": 0}

PROCESSOR_START_TIMEOUT = 1

INPUT_STREAM_QUEUE_SIZE = 100
INPUT_STREAM_RECEIVE_TIMEOUT = 1000
OUTPUT_STREAM_SEND_TIMEOUT = 1000

EPICS_PV_SUFFIX_IMAGE = ":FPICTURE"

DEFAULT_CAMERA_IMAGE_COLORMAP = "rainbow"
