package:
    name: psss_processing
    version: 1.6.1

source:
    path: ..

build:
    noarch: python
    number: 0
    script: python -m pip install --no-deps --ignore-installed .
    entry_points:
        - psss_processing = psss_processing.start_processing:main

requirements:
    build:
        - python
        - setuptools
        - pip

    run:
        - python
        - pyepics
        - bottle
        - bsread >=1.2.0
        - requests
        - numpy
        - scipy
        - numba

about:
    home: https://github.com/paulscherrerinstitute/psss_processing
