package:
    name: psss_processing
    version: 1.4.2

source:
    path: ..

build:
    number: 0

requirements:
    build:
        - python

    run:
        - python
        - pyepics
        - bottle
        - bsread >=1.2.0
        - requests
        - numba


build:
  entry_points:
    - psss_processing = psss_processing.start_processing:main

about:
    home: https://github.com/paulscherrerinstitute/psss_processing
