package:
    name: psss_processing
    version: 0.0.1

source:
    path: ..

build:
    number: 0

requirements:
    build:
        - python

    run:
        - python
        - cam_server
        - bottle
        - bsread >=1.2.0
        - requests

build:
  entry_points:
    - psss_processing = psss_processing.start_processing:main

about:
    home: https://github.com/paulscherrerinstitute/psss_processing
